/*
	Elastic CSS Framework
	Released under the MIT, BSD, and GPL Licenses.
	More information http://elasticss.com
	
	Elastic Engine

	@author     Fernando Trasviña (@azendal)
	@core team  Sergio de la Garza (@sgarza), Javier Ayala (@javi_ayala)
	@copyright  2009 Elastic CSS framework
	@version    2.0.2
*/
(function(d){var z=function(c,b){return window.getComputedStyle?window.getComputedStyle(c,b):c.currentStyle},A=function(c){var b=z(c).width;return b=="auto"||b.indexOf("px")<0?d(c).width():parseFloat(b)};window.Elastic=function c(b){var a,e,i,k,h,F,u,B,C,l,v,w,p,f,j,s,n,t,D,y,x,o,g,q,m,E,G=/(^|\s+)on\-(\d+)(\s+|$)/,H=/(^|\s+)span\-(\d+)(\s+|$)/,I=/(^|\s+)adaptive\-(\d+)\-(\d+)(\s+|$)/;f=[];a=0;C=d.find(".columns",b);i=0;for(F=C.length;i<F;i++){k=C[i];v=k.className;j=v.indexOf("on-")>-1&&G.test(v)?
Number(RegExp.$2):d.find("> .column, > .container > .column",k).length;k=d.find("> .container",k)[0]||k;l=A(k);s=l/j;n=Math.round(s);if(v.indexOf("adaptive-")>-1&&I.test(v)){u=Number(RegExp.$2);w=Number(RegExp.$3);if(n>w)for(;n>w;){j+=1;s=l/j;n=Math.round(s)}else if(n<u)for(;n<u;){j-=1;s=l/j;n=Math.round(s)}}w=d.find("> .column",k);k=0;for(u=w.length;k<u;k++){y=[];o=[];g=[];h=D=x=q=0;p=w[k];e=p.className;t=1;if(e.indexOf("span-")>-1&&H.test(e))t=Number(RegExp.$2);p.escol=t=t<=j?t:j;a+=t;if(a==j||
k==u-1||e.indexOf("final")>-1){f.push(p);h=1}else if(a<j)f.push(p);else if(a>j)D=h=1;if(h){h=0;for(B=f.length;h<B;h++){m=f[h];E=m.className;if(E.indexOf("fixed")>-1){y.push(m);x+=A(m)}else if(E.indexOf("elastic")>-1)o.push(m);else{g.push(m);m.style.width=m==f[B-1]?Math.round(s*m.escol)+"px":Math.round(n*m.escol)+"px";q+=A(m)}}h=o.length;if(h>0){g=l-(q+x);if(g<=0)continue;f=g/h;f=Math.round(f);e=f*h;for(a=0;a<h;a++)o[a].style.width=f+"px";if(e>g){e=e-g+1;for(a=1;a<e;a++)o[o.length-a].style.width=f-
1+"px"}else if(e<g){e=g-e+1;for(a=1;a<e;a++)o[o.length-a].style.width=f+1+"px"}for(a=f=0;a<h-1;a++)f+=Number(o[a].style.width.replace("px",""));o[h-1].style.width=l-(q+x+f)+"px"}else if(p.escol==j&&y.length===0)p.style.width=l+"px";else if(g.length>0&&y.length===0&&a==j){if(q>l){e=q-l+1;for(a=1;a<e;a++)g[g.length-a].style.width=(n-1)*g[g.length-a].escol+"px"}else if(q<l){e=l-q+1;for(a=1;a<e;a++)g[g.length-a].style.width=(n+1)*g[g.length-a].escol+"px"}for(a=f=0;a<g.length-1;a++)f+=Number(g[a].style.width.replace("px",
""));m.style.width=l-f+"px"}else if(a<j&&e.indexOf("final")>-1)p.style["margin"+(v.indexOf("inverted")>-1?"Left":"Right")]=l-q-x+"px";f=[];a=0}if(D){f=[p];a=t}}}for(i in c.helpers)c.helpers.hasOwnProperty(i)&&c.helpers[i](b)};var r=window.Elastic;r.version="2.0.3";r.reset=function(c){var b=d(document);b.trigger("elastic:beforeReset");var a,e,i;e=d.find(".same-height > *, .full-height, .elastic-height",c);a=0;for(i=e.length;a<i;a++)e[a].style.height="";e=d.find(".vertical-center, .center, .bottom",
c);a=0;for(i=e.length;a<i;a++){e[a].parentNode.style.paddingTop="";e[a].parentNode.style.height=""}e=d.find(".column:not(.fixed), .full-width",c);a=0;for(i=e.length;a<i;a++)e[a].style.width="";c=d.find(".column.final",c);a=0;for(e=c.length;a<e;a++){c[a].style.marginLeft="";c[a].style.marginRight=""}b.trigger("elastic:reset")};r.refresh=function(c){var b=d(document);b.trigger("elastic:beforeRefresh");r.reset(c);r(c);b.trigger("elastic:refresh")};r.configuration={refreshOnResize:true};r.helpers={"full-width":function(c){var b,
a=d.find(".full-width",c),e=a.length;for(c=0;c<e;c++){b=d(a[c]);b.width(b.parent().width()-(b.outerWidth(true)-b.width()))}},"same-height":function(c){d(".same-height",c).each(function(){var b=0;d("> *",this).each(function(){var a=d(this).outerHeight(true);b=b>a?b:a}).each(function(){d(this).css("height",b)})})},"full-height":function(c){d(".full-height",c).each(function(){var b=d(this);b.css("height",d(this.parentNode).height()-(b.outerHeight(true)-b.height()))})},"elastic-height":function(c){d(".elastic-height",
c).each(function(){var b=d(this),a=0;d("> *:not(.elastic-height)",this.parentNode).each(function(){a+=d(this).outerHeight(true)});b.css("height",Math.round(b.parent().height()-a));r.refresh(this)})},center:function(c){d(".vertical-center, .center",c).each(function(){var b=d(this.parentNode),a=Math.round((b.height()-d(this).outerHeight(true))/2);b.css({paddingTop:a+"px",height:b.css("height")?b.outerHeight()-a:""})})},bottom:function(c){d(".bottom",c).each(function(){var b=d(this.parentNode),a=Math.round(b.height()-
d(this).outerHeight(true));b.css({paddingTop:a+"px",height:b.css("height")?b.outerHeight()-a:""})})}};d(document).bind("elastic:beforeInitialize",function(){var c=/(^|\s+)display\s+([\w\_\-\d]+)(\s+|$)/;d(".display").each(function(){c.test(this.className);var b=".position-"+RegExp.$2;d(b).removeClass(b).appendTo(this)})})})(jQuery);
jQuery(window).bind("load",function(){var d=jQuery(document),z=document.body.clientWidth;d.trigger("elastic:beforeInitialize");Elastic();z!=document.body.clientWidth&&Elastic.refresh();jQuery(window).bind("resize",function(){Elastic.configuration.refreshOnResize&&Elastic.refresh()});d.bind("elastic",Elastic.refresh);d.trigger("elastic:initialize")});
